[package]
name = "file_hash"
description = "Displays the hash of each file"
version = "0.6.2"
edition = "2021"

[dependencies]
sha1 = "0.10.1"
sha2 = "0.10.2"
lla_plugin_sdk = { path = "../../sdk" }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
dirs.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lib]
crate-type = ["cdylib"]
