name = "light"
author = "Mohamed Achaq"
description = "A clean theme optimized for light terminals with carefully selected colors for maximum readability"

[colors]
file = { r = 71, g = 85, b = 105 }
directory = { r = 30, g = 64, b = 175 }
symlink = { r = 2, g = 132, b = 199 }
executable = { r = 22, g = 163, b = 74 }

size = { r = 22, g = 163, b = 74 }
date = { r = 124, g = 58, b = 237 }
user = { r = 190, g = 24, b = 93 }
group = { r = 100, g = 116, b = 139 }

permission_dir = { r = 30, g = 64, b = 175 }
permission_read = { r = 22, g = 163, b = 74 }
permission_write = { r = 194, g = 65, b = 12 }
permission_exec = { r = 190, g = 24, b = 93 }
permission_none = { r = 148, g = 163, b = 184 }

[special_files]
[special_files.folders]
"node_modules" = { r = 148, g = 163, b = 184 }
"target" = { r = 148, g = 163, b = 184 }
"dist" = { r = 148, g = 163, b = 184 }
".git" = { r = 190, g = 24, b = 93 }
"build" = { r = 148, g = 163, b = 184 }
".cache" = { r = 148, g = 163, b = 184 }

"*-env" = { r = 22, g = 163, b = 74 }
"venv" = { r = 22, g = 163, b = 74 }
".env" = { r = 22, g = 163, b = 74 }

"*.d" = { r = 30, g = 64, b = 175 }
"*_cache" = { r = 148, g = 163, b = 184 }
"*-cache" = { r = 148, g = 163, b = 184 }

[special_files.dotfiles]
".gitignore" = { r = 2, g = 132, b = 199 }
".env" = { r = 194, g = 65, b = 12 }
".dockerignore" = { r = 2, g = 132, b = 199 }
".editorconfig" = { r = 2, g = 132, b = 199 }
".prettierrc" = { r = 2, g = 132, b = 199 }
".eslintrc" = { r = 2, g = 132, b = 199 }
".babelrc" = { r = 2, g = 132, b = 199 }

[special_files.exact_match]
"Dockerfile" = { r = 2, g = 132, b = 199 }
"docker-compose.yml" = { r = 2, g = 132, b = 199 }
"Makefile" = { r = 190, g = 24, b = 93 }
"CMakeLists.txt" = { r = 190, g = 24, b = 93 }
"README.md" = { r = 194, g = 65, b = 12 }
"LICENSE" = { r = 194, g = 65, b = 12 }
"package.json" = { r = 194, g = 65, b = 12 }
"Cargo.toml" = { r = 190, g = 24, b = 93 }
"go.mod" = { r = 2, g = 132, b = 199 }
"flake.nix" = { r = 30, g = 64, b = 175 }
"flake.lock" = { r = 148, g = 163, b = 184 }
"shell.nix" = { r = 30, g = 64, b = 175 }
"default.nix" = { r = 30, g = 64, b = 175 }

[special_files.patterns]
"*rc" = { r = 2, g = 132, b = 199 }
"*.min.*" = { r = 148, g = 163, b = 184 }
"*.test.*" = { r = 22, g = 163, b = 74 }
"*.spec.*" = { r = 22, g = 163, b = 74 }
"*.lock" = { r = 148, g = 163, b = 184 }
"*.config.*" = { r = 2, g = 132, b = 199 }

[extensions.groups]
rust = ["rs", "toml"]
python = ["py", "pyi", "pyw", "ipynb"]
javascript = ["js", "mjs", "cjs", "jsx"]
typescript = ["ts", "tsx", "d.ts"]
java = ["java", "jar", "class"]
csharp = ["cs", "csx"]
cpp = ["cpp", "cc", "cxx", "c++", "hpp", "hxx", "h++"]
go = ["go"]
ruby = ["rb", "erb"]
php = ["php", "phtml"]
swift = ["swift"]
kotlin = ["kt", "kts"]
nix = ["nix"]

markup = ["html", "htm", "xhtml", "xml", "svg", "vue", "wasm", "ejs"]
style = ["css", "scss", "sass", "less", "styl"]
web_config = ["json", "json5", "yaml", "yml", "toml", "ini", "conf", "config"]

shell = ["sh", "bash", "zsh", "fish", "ps1", "psm1", "psd1"]
script = ["pl", "pm", "t", "tcl", "lua", "vim", "vimrc", "r"]

doc = [
    "md",
    "rst",
    "txt",
    "org",
    "wiki",
    "adoc",
    "tex",
    "pdf",
    "epub",
    "doc",
    "docx",
    "rtf",
]

image = ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "webp", "ico", "heic"]
video = ["mp4", "webm", "mov", "avi", "mkv", "flv", "wmv", "m4v", "3gp"]
audio = ["mp3", "wav", "ogg", "m4a", "flac", "aac", "wma"]

data = ["csv", "tsv", "sql", "sqlite", "db", "json", "xml", "yaml", "yml"]
archive = ["zip", "tar", "gz", "bz2", "xz", "7z", "rar", "iso", "dmg"]

[extensions.colors]
rust = { r = 190, g = 24, b = 93 }
python = { r = 22, g = 163, b = 74 }
javascript = { r = 194, g = 65, b = 12 }
typescript = { r = 30, g = 64, b = 175 }
java = { r = 190, g = 24, b = 93 }
csharp = { r = 22, g = 163, b = 74 }
cpp = { r = 190, g = 24, b = 93 }
go = { r = 2, g = 132, b = 199 }
ruby = { r = 190, g = 24, b = 93 }
php = { r = 22, g = 163, b = 74 }
swift = { r = 190, g = 24, b = 93 }
kotlin = { r = 22, g = 163, b = 74 }
nix = { r = 30, g = 64, b = 175 }

markup = { r = 124, g = 58, b = 237 }
style = { r = 2, g = 132, b = 199 }
web_config = { r = 194, g = 65, b = 12 }

shell = { r = 22, g = 163, b = 74 }
script = { r = 194, g = 65, b = 12 }

doc = { r = 71, g = 85, b = 105 }

image = { r = 124, g = 58, b = 237 }
video = { r = 124, g = 58, b = 237 }
audio = { r = 124, g = 58, b = 237 }

data = { r = 194, g = 65, b = 12 }
archive = { r = 190, g = 24, b = 93 }

rs = { r = 190, g = 24, b = 93 }
py = { r = 22, g = 163, b = 74 }
js = { r = 194, g = 65, b = 12 }
ts = { r = 30, g = 64, b = 175 }
jsx = { r = 194, g = 65, b = 12 }
tsx = { r = 30, g = 64, b = 175 }
vue = { r = 22, g = 163, b = 74 }
css = { r = 2, g = 132, b = 199 }
scss = { r = 2, g = 132, b = 199 }
html = { r = 124, g = 58, b = 237 }
md = { r = 71, g = 85, b = 105 }
json = { r = 194, g = 65, b = 12 }
yaml = { r = 194, g = 65, b = 12 }
toml = { r = 194, g = 65, b = 12 }
sql = { r = 2, g = 132, b = 199 }
