# lla poimandres theme
name = "poimandres"
author = "Mohamed Achaq"
description = "A theme inspired by the Poimandres color scheme, featuring a deep space aesthetic with vibrant accents"

[colors]
# Core UI Elements
file = "#A6ACAE"       # foreground - Soft gray for files
directory = "#89AFFF"  # blue - Directories
symlink = "#89DBFF"    # cyan - Symlinks
executable = "#5DE4B3" # green - Executables

# Metadata
size = "#5DE4B3"  # green - File sizes
date = "#FCBCFA"  # magenta - Dates
user = "#D0679D"  # red - User
group = "#8A9092" # dim-foreground - Group

# Permissions
permission_dir = "#89AFFF"   # blue - Directory permissions
permission_read = "#5DE4B3"  # green - Read permissions
permission_write = "#FFFFC2" # yellow - Write permissions
permission_exec = "#D0679D"  # red - Execute permissions
permission_none = "#282E30"  # dim-black - No permissions

[special_files]
# Special Folders
[special_files.folders]
# Development folders
"node_modules" = { h = 0, s = 0, l = 0.3 } # Dark gray using HSL
"target" = "#282E30"                       # dim-black
"dist" = "#282E30"                         # dim-black
".git" = "#D0679D"                         # red
"build" = "#282E30"                        # dim-black
".cache" = "#282E30"                       # dim-black
"*-env" = "#5DE4B3"                        # green
"venv" = "#5DE4B3"                         # green
".env" = "#5DE4B3"                         # green
"*.d" = "#89AFFF"                          # blue - Type definition folders
"*_cache" = "#282E30"                      # dim-black - Cache folders
"*-cache" = "#282E30"                      # dim-black - Cache folders

# Dotfiles
[special_files.dotfiles]
".gitignore" = "#89DBFF"    # cyan
".env" = "#FFFFC2"          # yellow
".dockerignore" = "#89DBFF" # cyan
".editorconfig" = "#89DBFF" # cyan
".prettierrc" = "#89DBFF"   # cyan
".eslintrc" = "#89DBFF"     # cyan
".babelrc" = "#89DBFF"      # cyan

# Exact matches
[special_files.exact_match]
"Dockerfile" = "#89DBFF"         # cyan
"docker-compose.yml" = "#89DBFF" # cyan
"Makefile" = "#D0679D"           # red
"CMakeLists.txt" = "#D0679D"     # red
"README.md" = "#FFFFC2"          # yellow
"LICENSE" = "#FFFFC2"            # yellow
"package.json" = "#FFFFC2"       # yellow
"Cargo.toml" = "#D0679D"         # red
"go.mod" = "#89DBFF"             # cyan
"flake.nix" = "#89AFFF"          # blue
"flake.lock" = "#282E30"         # dim-black
"shell.nix" = "#89AFFF"          # blue
"default.nix" = "#89AFFF"        # blue

# Pattern matches
[special_files.patterns]
"*rc" = "#89DBFF"        # cyan
"*.min.*" = "#282E30"    # dim-black
"*.test.*" = "#5DE4B3"   # green
"*.spec.*" = "#5DE4B3"   # green
"*.lock" = "#282E30"     # dim-black
"*.config.*" = "#89DBFF" # cyan

[extensions.groups]
# Development files
rust = ["rs", "toml"]
python = ["py", "pyi", "pyw", "ipynb"]
javascript = ["js", "mjs", "cjs", "jsx"]
typescript = ["ts", "tsx", "d.ts"]
java = ["java", "jar", "class"]
csharp = ["cs", "csx"]
cpp = ["cpp", "cc", "cxx", "c++", "hpp", "hxx", "h++"]
go = ["go"]
ruby = ["rb", "erb"]
php = ["php", "phtml"]
swift = ["swift"]
kotlin = ["kt", "kts"]
nix = ["nix"]

# Web files
markup = ["html", "htm", "xhtml", "xml", "svg", "vue", "wasm", "ejs"]
style = ["css", "scss", "sass", "less", "styl"]
web_config = ["json", "json5", "yaml", "yml", "toml", "ini", "conf", "config"]

# Shell and scripts
shell = ["sh", "bash", "zsh", "fish", "ps1", "psm1", "psd1"]
script = ["pl", "pm", "t", "tcl", "lua", "vim", "vimrc", "r"]

# Documentation
doc = [
    "md",
    "rst",
    "txt",
    "org",
    "wiki",
    "adoc",
    "tex",
    "pdf",
    "epub",
    "doc",
    "docx",
    "rtf",
]

# Media files
image = ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "webp", "ico", "heic"]
video = ["mp4", "webm", "mov", "avi", "mkv", "flv", "wmv", "m4v", "3gp"]
audio = ["mp3", "wav", "ogg", "m4a", "flac", "aac", "wma"]

# Data and config
data = ["csv", "tsv", "sql", "sqlite", "db", "json", "xml", "yaml", "yml"]
archive = ["zip", "tar", "gz", "bz2", "xz", "7z", "rar", "iso", "dmg"]

[extensions.colors]
# Development
rust = "#D0679D"       # red
python = "#5DE4B3"     # green
javascript = "#FFFFC2" # yellow
typescript = "#89AFFF" # blue
java = "#D0679D"       # red
csharp = "#5DE4B3"     # green
cpp = "#D0679D"        # red
go = "#89DBFF"         # cyan
ruby = "#D0679D"       # red
php = "#5DE4B3"        # green
swift = "#D0679D"      # red
kotlin = "#5DE4B3"     # green
nix = "#89DBFF"        # cyan

# Web
markup = "#FCBCFA"     # magenta
style = "#89DBFF"      # cyan
web_config = "#FFFFC2" # yellow

# Shell and scripts
shell = "#5DE4B3"  # green
script = "#FFFFC2" # yellow

# Documentation
doc = "#A6ACAE" # foreground

# Media
image = "#FCBCFA" # magenta
video = "#FCBCFA" # magenta
audio = "#FCBCFA" # magenta

# Data and config
data = "#FFFFC2"    # yellow
archive = "#D0679D" # red

# Individual extension overrides
rs = "#D0679D"   # red
py = "#5DE4B3"   # green
js = "#FFFFC2"   # yellow
ts = "#89AFFF"   # blue
jsx = "#FFFFC2"  # yellow
tsx = "#89AFFF"  # blue
vue = "#5DE4B3"  # green
css = "#89DBFF"  # cyan
scss = "#89DBFF" # cyan
html = "#FCBCFA" # magenta
md = "#A6ACAE"   # foreground
json = "#FFFFC2" # yellow
yaml = "#FFFFC2" # yellow
toml = "#FFFFC2" # yellow
sql = "#89DBFF"  # cyan
