#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

output_file="${1:-docs/plugins/catalog.md}"
output_dir="$(dirname "$output_file")"
mkdir -p "$output_dir"

temporary_file="$(mktemp "${TMPDIR:-/tmp}/lla-plugin-catalog.XXXXXX")"
trap 'rm -f "$temporary_file"' EXIT

{
    printf '%s\n\n' '# Bundled plugin catalog'
    printf '%s\n\n' '<!-- Generated by scripts/generate_plugins.sh. Do not edit manually. -->'
    printf '%s\n\n' 'These plugins are built and verified as part of every lla release.'

    for manifest in plugins/*/plugin.toml; do
        plugin_dir="$(dirname "$manifest")"
        slug="$(basename "$plugin_dir")"
        name="$(awk -F '"' '/^name[[:space:]]*=/{print $2; exit}' "$manifest")"
        id="$(awk -F '"' '/^id[[:space:]]*=/{print $2; exit}' "$manifest")"
        description="$(awk -F '"' '/^description[[:space:]]*=/{print $2; exit}' "$manifest")"

        if [[ -z "$description" ]]; then
            description="No description provided."
        fi

        printf -- '- [`%s`](../../plugins/%s/README.md) — %s (`%s`)\n' \
            "$name" "$slug" "$description" "$id"
    done
} > "$temporary_file"

chmod 0644 "$temporary_file"
mv "$temporary_file" "$output_file"
trap - EXIT

echo "Generated $output_file"
